apiVersion: v1 
kind: Pod
metadata:
  name: test-pod
  labels:
    app: "test"
spec:
  containers:
  - name: container1
    image: nginxdemos/hello:plain-text
    ports:
    - containerPort:  80
      name:  http
    volumeMounts:
    - name: myapptemp
      mountPath: /app123
  volumes:
    - name: myapptemp
      emptyDir: 
  restartPolicy: Always