apiVersion: v1
kind: Namespace
metadata:
  name:  testns

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: testns
  name: myreplicaset1
  labels:
    app: myapp
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: l1
  template:
    metadata:
      labels:
        app: l1
    spec:
      containers:
      - name: myapp
        image: nginx:1.14.2 #first version>>>1.16.1
