apiVersion: v1 #version of the k8s API to use
kind: Pod #what kind of resource we are deploying
metadata: #information about the resource
  name: pod11 #name of the resource
  labels: #additional data for management
    app: ordering
    env: prod
spec: #specifiaction of the resource
  containers: #list of containers to use
    - name: pod11-container #run time container name
      image: nginxdemos/hello #image to pull from registry image:version
      ports: #port data of the container
      - name:  http-port #port name
        port:  80 #port no to use
        protocol: TCP #protocol to use
        
