apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset1
  labels:
    app: myapp
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: l1
  template:
    metadata:
      labels:
        app: l1
    spec:
      containers:
      - name: myapp
        image: nginx
