apiVersion: v1
kind: Service
metadata:
  name: "cip-{{ .Values.name }}"
  namespace: "{{ .Values.ns }}"
spec:
  selector:
    env: prod
  type: ClusterIP
  ports:
  - name: demosport
    protocol: TCP
    port: {{ .Values.portno }} #clusterip port
    targetPort: 80