# Default values for p1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
ns: default
name: demo
# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
rc: 1
portno: 9999
image: nginx:latest
